name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Release Version
        id: getReleaseVersion
        run: echo tag=${GITHUB_REF#refs/*/v} >> $GITHUB_OUTPUT

      - name: Echo version
        run: echo ${{ steps.getReleaseVersion.outputs.tag }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Package Nuget
        run: dotnet pack -p:PackageVersion=${{ steps.getReleaseVersion.outputs.tag }} -o ./output

      - name: Push Nuget Package
        run: dotnet nuget push ./output/TinyHealthCheck.${{ steps.getReleaseVersion.outputs.tag }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json

      ## Checkout so we can apply the new tag
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      ## Documentation: https://github.com/marvinpinto/action-automatic-releases
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
